exclude_paths:
  - tmp
  - vendor

detectors:
  LongParameterList:
    enabled: false
  FeatureEnvy:
    exclude:
      - Inspectable::Sanitizers::Dater#exclude_and_transform
      - Inspectable::Sanitizers::Structer#exclude_and_transform
