exclude_paths:
  - tmp
  - vendor

detectors:
  ControlParameter:
    exclude:
      - Inspectable::Builder#included
  LongParameterList:
    enabled: false
  FeatureEnvy:
    exclude:
      - Inspectable::Sanitizers::Data#exclude_and_transform
      - Inspectable::Sanitizers::Struct#exclude_and_transform
  TooManyStatements:
    exclude:
      - Inspectable::Builder#initialize
      - Inspectable::Builder#define_inspect
